services:
  hpvsim:
    build: .
    image: hpvsim_rwanda
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - ./results:/app/results
      - ./figures:/app/figures
    stdin_open: true
    tty: true
    command: uvicorn run_rest_api:app --host 0.0.0.0 --port 8000
